export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const REQUEST_CHARACTER_DATA = "REQUEST_CHARACTER_DATA";
export const RECEIVED_API_DATA = "RECEIVED_API_DATA";
export const RECEIVED_CHARACTER_DATA = "RECEIVED_CHARACTER_DATA";
